{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudforge.name" . }}
  labels:
    {{- include "cloudforge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cloudforge.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}

